# Generated by Django 5.1.4 on 2026-05-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='background',
            field=models.ImageField(blank=True, upload_to='scenes/'),
        ),
    ]
