# Generated by Django 5.1.4 on 2026-05-30 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0002_alter_scene_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='memorials.memorial')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'memorial'), name='unique_user_memorial_candle'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'memorial'), name='unique_session_memorial_candle')],
            },
        ),
    ]
