# Generated by Django 5.1.4 on 2026-06-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0004_tribute_is_approved_tribute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
